### ISSUE TITLE
Pet exercise- Byron

### ISSUE THREAD

**Issue by jairrab** [jairrab/AndroidClass#4]
- Checkout beta-jay branch in Android Studio
- Update the branch with latest changes from git
- Create a branch with jay-beta as parent branch using following name: _beta-yourname_ (e.g. beta-rex)
- While working on your own branch, create a directory under _com.github.jairrab.testapp.petexercise_ with your name
  - See directory _jay_ under _com.github.jairrab.testapp.petexercise_. This will be your example.
- Under your directory, create a class PetOfYourName (e.g. class PetOfJemboy) that extends the class Pet
  - see the class PetOfJay under _com.github.jairrab.testapp.petexercise.jay_ for example
  - Make sure your class does not have any errors. You will need to override some classes from the base Pet class (AS will be your friend in identifying and fixing the errors)
- When everything is done, commit all your changes and push all changes (which should also include the new branch) to GitHub.
- Mark this GitHub task as complete

**Comment by shkadush** [comment]
Complete
