### ISSUE TITLE
LinearLayout Exercise

### ISSUE THREAD

**Issue by jairrab** [jairrab/AndroidClass#7]
![Imgur](https://i.imgur.com/HR7A4LZ.png)

1. Create a branch with beta-jay as parent branch : linearlayout-yourname (linearlayout-ron)
2. Create an xml layout file on res\layout folder with the name linearlayout_exercise_yourname.xml ( linearlayout_exercise_ron.xml)
3. Create the layout above in XML using LinearLayout
4. Commit your branch and code updates
5. Add a comment to this issue TASK COMPLETE

**Comment by rmontalba** [comment]
TASK COMPLETE

**Comment by jepogoy** [comment]
Task complete

**Comment by shkadush** [comment]
Done layout. But I cannot get the vertical 5dp margin. Every linear layout has some vertical gap.

**Comment by jairrab** [comment]
Closing this issue. Good job.
