### ISSUE TITLE
ConstraintLayoutExercise

### ISSUE THREAD

**Issue by jairrab** [jairrab/AndroidClass#8]
![ConstraintLayout Pet Exercise](https://i.imgur.com/TrkmIbU.png)

- Create a new branch _constraintlayout_yourname_ using _beta-jay_ as the parent branch
- Create an xml file _constraintlayout_yourname_ under _res/layout_ and implement the picture above in ConstraintLayout
- Commit your changes and push your new branch to GitHub
- Create a _pull request_ for your new branch in Github targeting _beta-jay_ as the branch to merge into
- Add a comment to this issue TASK_COMPLETE

**Important**
- I need at least 4 people to complete the exercise before we conduct our next session
- Please ask questions

**Comment by rmontalba** [comment]
TASK_COMPLETE

**Comment by roncalapis** [comment]
TASK_COMPLETE

sir I also have a Linear Layout on the same branch that I would like to make a simple game, I am not happy with the cluttered layout so will try a new one -- but on the next meeting can you discuss how layouts are actually used in the app. I imagine that for a simpler layout to work it will actually switch between layouts so only what is needed by the user will show up

**Comment by jairrab** [comment]
> TASK_COMPLETE
> 
> I imagine that for a simpler layout to work it will actually switch between layouts so only what is needed by the user will show up

Switch between layouts? Once an activity has been assigned a content view in onCreate(), this cannot be changed during the lifetime of the activity.

Perhaps your looking at changing the states of the child views inside the layout. 

BTW, please a file a PR for the branch.

**Comment by roncalapis** [comment]
ok Sir, will send more detail later tonight on how I visualize the app to
work.

Done with creation of PR. Thanks!

**Comment by shkadush** [comment]
Task complete
